<?php 
namespace gamut;

new viewCMSContent ();

echo U_DOCTYPE.
	U_HTML_OPEN .
	U_HEAD_OPEN .
		U_META .
		U_META_KEYWORDS .
		U_META_DESCRIPTION .
		U_META_TITLE_OPEN .
		U_META_TITLE .
		U_META_TITLE_CLOSE .
		U_HEAD .		
	U_HEAD_CLOSE .
	flush(); 

echo U_BODY_OPEN.
	U_CONTAINER_OPEN.
	U_SKIP_LINKS.
	U_HEADER_OPEN.
		U_HEADER.
	U_HEADER_CLOSE.
	U_MAIN_OPEN.
	U_CONTENT_OPEN.
	PAGE_TITLE.
	PAGE_CONTENT;
	